init:
	# make /var/run/dusa directory
	# make /var/dusa directory
	# make user dusa and group dusa
	# patch daemon file with the uid and gid of the dusa user
	# setcap cap_chown=ep /path/to/your/program to the daemon bin
	
build:
	# cargo build release all of the file
	# move daemon files to /usr/bin/dusad
	# move the cli to /usr/local/dusa
	# setcap 
